### ISSUE TITLE
First draft of paper and appendix

### ISSUE THREAD

**Issue by athowes** [athowes/naomi-aghq#55]
# Paper

* [ ] Better description of ART attendance
* [x] Collected together version
* [ ] Table of why each ELGM reason is important. And which section of the model it effects. Perhaps what problems I would expect it to be likely to cause.
* [x] Connection of Laplace to AGHQ with `k = 1`
* [x] Complete mathematical details of PCA-AGHQ
* [ ] Description of Laplace marginals (in conclusion / future work)
* [x] Alter Naomi results plot to have larger text (as is the case for BioInference poster)
* [x] Check posterior contraction results #45 
* [ ] Group posterior contraction plot by model component (and probably move to appendix)
* [ ] Add KS plot and text from `.csv`
* [ ] Add Anderson-Darling (plot and text) #51 
* [ ] Add PSIS (plot and text) #41
* [ ] Further discussion of MMD -- what does this reduction practically speaking mean? Is there a way to interpret it? #42 
  * [ ] Make the numbers inline! 
* [ ] Further look into standard deviation implications: what does the fact that TMB underestimates SD mean for HIV policy? Select the nodes which are the most underestimated
  * [ ] Something to do here: colour the points by parameter in the mean and SD point estimates latent plot. Could just do the parameters which are outlying
* [ ] ~~Is there a third exceedance probability case-study to add?~~

# Appendix

* [x] Use bold for vectors and matrices throughout
* [ ] $51 + 14n$ versus $51 + 13n$ confusion
* [x] All many termed equations into tables
* [ ] All observations as $y$ (and generally align notation with main text)
* [ ] Create DAG
* [ ] Complete dependence input table
* [x] Any more MCMC diagnostics to add?
* [ ] Normalising constant AGHQ and PCA-AGHQ section
* [ ] Further inference comparison results detailed tables
  * [x] Point estimates latent and output
  * [ ] Add output to KS

**Comment by athowes** [comment]
Add mathematics of how the Choleksy and spectral decomposition AGHQ interact with the number of points in the marginal dimensions!
